[package]
name = "nginx-module"
version = "0.2.0"
authors = ["Sehyo Chang   sehyo@nginx.com"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.37"
quote = "1.0.18"
syn = { version = "1.0.92", features = ["visit"] }
