[package]
name = "cache-clean-rs"
version = "0.1.0"
authors = ["David Coles <coles.david@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
nginx-rs = { path = "../../nginx-rs", features = ["with-compat"] }

[profile.release]
debug = true
